#cloud-config
#set Hostname
hostname: CoreBM2
#set SSH key
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD5daCn24slNsbTQlq87jexrFdsanqB/lS1vqtu2Dsg3eGPIxSiKyzgpxgPrkLG6QYAEp6IRdwNDMYN2FIxqiQaBQXs8uxl6Ix3QO6xzbA3GRZ2fLW9te5WuOH+5WS7Kv20jUVwsxHmzxxfGQK/vl3KGtdXgegWoTNgPMjo1E25sG0R+5kUnJBlTya2Nql7GRDQ0GqPcNt//vOU3EIHDZ6AGjwvJ5F1635qNW/M1mgZGOCXlUXDiXFWWNz76z6C0qknmxqN68POP5JuOaA7XXffYcEbtFjPORFtQV474TYKZkXQjF4fVqfxP92uOzkltNt22RgX1/G2KUb/DUZOoS2d csc573pod5b@csc573pod5b-Precision-WorkStation-T3400

- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnN8ZPC9fp6ZpIaUlKVHlVswWakMflQWvEe/hpSr3n/EJIJfXm3xldIgYGcPv0Fwj5Ohw0tNqyiI6D9j1sIVd/3iUkDPPg1al7ELxoFvpgV1ozYE4HYHq/aVl1bjIohyoRM3rYU7gAcYFsfj1+FlmwaN2wKAujKjEpYAseAJjF6wyA9u1q/uVtLKKiAt2H7izOck0EQB98UmTQkLbGmyCh6ORUeaw/BW9fKbJlwapfogYUrrjk9W1diXnUm0f+Za+lm4LoPMuMIIbp18LhTsSyt7goSDeLHAGlVoCL8xsah0UJd9KtSSSMNRYHB4ERX1yysK9QToEWzLx7qRI+0tD/ csc573pod5b@csc573pod5b-Precision-WorkStation-390

coreos:
 units:
 - name: eno1.network
   runtime: true
   content: |
    [Match]
    Name = eno1
    [Network]
    Address = 192.168.1.3/24


coreos:
 etcd2:
  # Generate a new token for each unique cluster from https://discovery.etcd.io/new?size=2
  # specify the initial size of your cluster with ?size=X
  discovery: https://discovery.etcd.io/b407afa046bd6cabb48d18119309c59e
  #Advertise client urls on the given interface and port
  #Advertise peer url on the same interface and port
  advertise-client-urls: http://192.168.1.3:2379
  initial-advertise-peer-urls: http://192.168.1.3:2380
  # listen on both the official ports and the legacy ports
  # legacy ports can be omitted if your application doesn't depend on them
  listen-client-urls: http://192.168.1.3:2379,http://127.0.0.1:2379,http://192.168.1.3:4001,http://127.0.0.1:4001
  listen-peer-urls: http://192.168.1.3:2380

 units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
